### ISSUE TITLE
TLS handshake failure on manual and gitops deployment for DICOM traffic

### ISSUE THREAD

**Issue by digihunch** [digihunch/korthweb#9]
It appears that with cert-manager generated credentials, the web port test is good. But DICOM echo test fails with TLS error:
```
16:50:08.963 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to dicom.orthweb.com:11112
storescu: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at org.dcm4che3.net.Connection.createTLSSocket(Connection.java:1157)
	at org.dcm4che3.net.Connection.connect(Connection.java:1050)
	at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:629)
	at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:649)
	at org.dcm4che3.tool.storescu.StoreSCU.open(StoreSCU.java:542)
	at org.dcm4che3.tool.storescu.StoreSCU.main(StoreSCU.java:285)
```

This is because the algorithm is ECDSA, and dcm4che client only supports RSA algorithm.

**Comment by digihunch** [comment]
Fixed in commit e6a94be
